AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: CodeDeployApp-prod
      ComputePlatform: Server

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApp
      DeploymentGroupName: DeploymentGroup-prod
      ServiceRoleArn: arn:aws:iam::222222222222:role/CodeDeployServiceRole
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      Ec2TagFilters:
        - Key: Environment
          Value: prod
          Type: KEY_AND_VALUE
