AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: CodeDeployApp-dev
      ComputePlatform: Server

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApp
      DeploymentGroupName: DeploymentGroup-dev
      ServiceRoleArn: arn:aws:iam::111111111111:role/CodeDeployServiceRole
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      Ec2TagFilters:
        - Key: Environment
          Value: dev
          Type: KEY_AND_VALUE
