-
  name: play1
  hosts: localhost
  tasks:
    - name: Exceute command of 'Date'
      command: date
    
    - name: Install httpd package
      yum:
        name: httpd
        state: present

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: yes
     